### PR TITLE
Fix macos compilation

### PR DESCRIPTION
**Pull request by nosnilmot**
Addresses https://github.com/processone/erlang-sqlite3/pull/6#issuecomment-768918167 - I'm not sure why it didn't show up before, definitely one of those "how did it ever work!?" moments.

### CODE REVIEW

**Comment by mremond** [comment]
Thanks !
@prefiks fixed it in last commit. Do you think we need this one too ?

**Comment by nosnilmot** [comment]
> @prefiks fixed it in last commit. Do you think we need this one too ?

@prefiks fix results in two DRV_CFLAGS entries in port_env that could match for compiling on macos/darwin. At the very least this can result in duplicated CFLAGS (although currently just -W flags, so it's harmless).

I have previously seen problems with port_specs sources when they were not mutually exclusive for darwin vs. non-darwin, (which one was picked seemed to be non-deterministic, especially when running ejabberd eunit tests) but I don't know if that would happen here too.

**Comment by prefiks** [comment]
Afaik, there would be not duplications, rule for darwin will use general rules (since we use $DRV_CFLAGS), and adds only -I... flag so difference between darwin and general case will be only that -I...

**Comment by nosnilmot** [comment]
See duplication of `-Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes` below:
```
$ cat compile_commands.json 
[
{ "file"      : "c_src/sqlite3_drv.c"
, "directory" : "/Users/stu/dev/erlang-sqlite3"
, "command"   : "cc -c -g -Wall -fPIC -MMD -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/lib/erl_interface-4.0.1/include\" -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/erts-11.1.5/include\" -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -Isqlite3_amalgamation -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes c_src/sqlite3_drv.c -o c_src/sqlite3_drv.o"
},
{ "file"      : "sqlite3_amalgamation/shell.c"
, "directory" : "/Users/stu/dev/erlang-sqlite3"
, "command"   : "cc -c -g -Wall -fPIC -MMD -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/lib/erl_interface-4.0.1/include\" -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/erts-11.1.5/include\" -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -Isqlite3_amalgamation -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes sqlite3_amalgamation/shell.c -o sqlite3_amalgamation/shell.o"
},
{ "file"      : "sqlite3_amalgamation/sqlite3.c"
, "directory" : "/Users/stu/dev/erlang-sqlite3"
, "command"   : "cc -c -g -Wall -fPIC -MMD -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/lib/erl_interface-4.0.1/include\" -I\"/usr/local/Cellar/erlang/23.2.1/lib/erlang/erts-11.1.5/include\" -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -Isqlite3_amalgamation -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes sqlite3_amalgamation/sqlite3.c -o sqlite3_amalgamation/sqlite3.o"
}
]

```

**Comment by prefiks** [comment]
Yes if you include -Wall... inside rule for darwin as you did here then you will get duplicates, but if you make it like i did in this commit: https://github.com/processone/erlang-sqlite3/commit/d9324133b3edc26d76f0f9ba423711688514d68c then there will be no duplicates.

**Comment by nosnilmot** [comment]
> Yes if you include -Wall... inside rule for darwin as you did here then you will get duplicates, but if you make it like i did in this commit: [d932413](https://github.com/processone/erlang-sqlite3/commit/d9324133b3edc26d76f0f9ba423711688514d68c) then there will be no duplicates.

oh, yes, sorry, bad merge here. all good, carry on :)

**Pull request closed without merging**
